name: Terraform Destroy Flask App

on:
  workflow_dispatch:

jobs:
  terraform-destroy:
    name: Destroy Infrastructure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5  # or any version you want

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init
        working-directory: Deployment

      - name: Terraform Destroy
        run: |
          terraform destroy \
            -var="key_pair_name=${{ secrets.KEY_PAIR_NAME }}" \
            -var="ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}" \
            --auto-approve
        working-directory: Deployment
