name: Terraform Destroy Flask App

on:
  workflow_dispatch:

jobs:
  terraform-destroy:
    name: Destroy Infrastructure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Terraform Init
        run: terraform init -backend-config=terraform.tfvars
      - name: Terraform Destroy
        run: terraform destroy -var-file=terraform.tfvars -auto-approve

