name: Terraform Plan and Apply

on:
  workflow_dispatch:  # Manual trigger from GitHub Actions UI

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    outputs:
      plan_status: ${{ steps.plan.outcome }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: Deployment

      - name: Terraform Plan
        id: plan
        run: terraform plan -var="key_pair_name=${{ secrets.KEY_PAIR_NAME }}"
        working-directory: Deployment

  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: plan
    if: needs.plan.result == 'success'  # ✅ Only run if Plan job succeeded

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: Deployment

      - name: Terraform Apply
        run: terraform apply -var="key_pair_name=${{ secrets.KEY_PAIR_NAME }}" --auto-approve
        working-directory: Deployment
