name: Terraform Automation for Flask Application on AWS

on:
  workflow_dispatch:  # Enables manual execution from GitHub UI

jobs:
  terraform-apply:
    name: Terraform Apply (Manual)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Set environment
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Gather credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_KEY_PAIR: ${{ secrets.AWS_KEY_PAIR }}

      - name: Terraform Init
        run: terraform init -backend-config=terraform.tfvars

      - name: Terraform Apply
        run: terraform apply -var-file=terraform.tfvars -auto-approve -auto-approve
